import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import products from '../products.json';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MEG SHOP</title>
        <meta name="E-commerce shop" content="Generated by create next app" />
        <link rel="icon" href="/baby.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MEG Shop!</h1>

        <p className={styles.description}>High-quality clothing for babies.</p>

        <ul className={styles.grid}>
          {products.map((product) => {
            const { id, title, image, price } = product;
            return (
              <li key={id} className={styles.card}>
                <a href="#">
                  <img src={image} alt={title} />
                  <h3>{title}</h3>
                  <p>${price}</p>
                  <p>
                    <button
                      className={styles.button}
                      onClick={() => addToCart({ id })}
                    >
                      Buy
                    </button>
                  </p>
                </a>
              </li>
            );
          })}
        </ul>
      </main>

      <footer>
        <section className={styles.footer}>
          Made by{' '}
          <a
            href="https://github.com/hakangundogdu"
            target="_blank"
            rel="noreferrer"
          >
            Hakan Gundogdu
          </a>
        </section>
      </footer>
    </div>
  );
}
